version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
    command: /bin/bash -c "while sleep 1000; do :; done"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single.node
    ports:
      - "9200:9200"
      - "9300:9300"
